name: Tweet to Discord

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install cheerio
      - run: node tweet.js
        env:
          TWITTER_USER: ${{ secrets.TWITTER_USER }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
